version: '3.8'

services:
  fastapi_app:
    build: ./app/v1
    ports:
      - "9090:9090"
    networks:
      - myserver_api_net
    volumes:
      - ./app/v1:/app
      - service_logs:/service_logs

  springboot_app:
    build: ./app/v2
    ports:
      - "9091:9091"
    networks:
      - myserver_api_net
    volumes:
      - service_logs:/service_logs

volumes:
  service_logs:

networks:
  myserver_api_net:
    external: true
