version: '3.8'

services:
  fastapi_app:
    build: ./app/v1
    ports:
      - "9090:9090"
    networks:
      - myserver_service_net
    volumes:
      - service_logs:/service_logs

  springboot_app:
    build: ./app/v2
    ports:
      - "9091:9091"
    networks:
      - myserver_service_net
    volumes:
      - service_logs:/service_logs

  nginx_gateway:
    image: nginx:latest
    ports:
      - "9080:80"
    volumes:
      - service_logs:/logs
    depends_on:
      - fastapi_app
      - springboot_app
    networks:
      - myserver_service_net

volumes:
  db_data:
  service_logs:

networks:
  myserver_api_net:
    external: true
