version: '3.8'

services:
  fastapi_app:
    build: ./app/v1
    expose:
      - 9090
    depends_on:
      - database

  springboot_app:
    build: ./app/v2
    expose:
      - 9091
    depends_on:
      - database

  nginx_gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/gateway.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi_app
      - springboot_app

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_user_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
