"""Model 수정

Revision ID: f362b0b9425c
Revises: b56b8797c482
Create Date: 2023-12-01 14:55:16.440589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f362b0b9425c'
down_revision: Union[str, None] = 'b56b8797c482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('COURSE', 'course_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=90),
               existing_nullable=False)
    op.alter_column('COURSE', 'course_description',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('USER', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('USER', 'real_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('USER', 'real_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('USER', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('COURSE', 'course_description',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('COURSE', 'course_name',
               existing_type=sa.String(length=90),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
